export const FETCH_TESTNETS = 'FETCH_TESTNETS';
export const FETCH_TESTNETS_SUCCESS = 'FETCH_TESTNETS_SUCCESS';
export const FETCH_TESTNETS_ERROR = 'FETCH_TESTNETS_ERROR';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_SORTBY = 'UPDATE_SORTBY';
